Repository rmdnps10/ATC2024, pull requests merged in 2024-09, with the labels that each got.

#1 Triggher Deployment looking at dev
  .github/workflows/dev-publish.yml
  .github/workflows/main-publish.yml
  .gitignore
  netlify.toml
Labels: Test

#3 프로젝트 기초 세팅 완료 및 헤더 구현
  .github/workflows/deprecated/dev-publish.yml
  .gitignore
  .husky/prepare-commit-msg
  README.md
  public/icon/.gitkeep
  public/images/.gitkeep
  public/images/staff-profile/.gitkeep
  public/logo/atc-logo.svg
  public/next.svg
  public/vercel.svg
  src/app/(main)/Header.js
  src/app/(main)/Header.module.css
  src/app/(main)/about/page.js
  src/app/(main)/about/page.module.css
  src/app/(main)/archive/page.js
  src/app/(main)/credit/page.js
  src/app/(main)/layout.js
  src/app/(main)/map/page.js
  src/app/(main)/page.js
  src/app/(main)/program/page.js
  src/app/(main)/work/[id]/page.js
  src/app/(main)/work/page.js
  src/app/(onboard)/layout.js
  src/app/(onboard)/onboard/page.js
  src/app/api/.gitkeep
  src/app/onboard/layout.js
  src/app/onboard/page.js
  src/hooks/.gitkeep
  src/lib/.gitkeep
  src/lib/connect-db.js
  src/models/.gitkeep
  src/style/global.css
  src/utils/.gitkeep
Labels: Feature, Docs, Style

#4 dev와 main 동기화
  README.md
  src/app/(main)/Header.js
Labels: Deployment

#9 Main 페이지 셋팅 및 테스트
  README.md
  package-lock.json
  package.json
  public/model/fishfast.glb
  public/model/fishswim.glb
  src/app/(main)/page.js
  src/app/(main)/page.module.css
  src/components/main/Experience.js
Labels: Style
