Repository rmdnps10/ATC2024, pull requests merged in 2024-10, with the labels that each got.

#16 Sprint/works page#5
  .eslintrc.json
  package-lock.json
  package.json
  public/images/Rectangle.jpg
  public/images/Rectangle10.jpg
  public/images/Rectangle13.jpg
  public/logo/atc-title.svg
  public/logo/axt-logo.png
  src/app/(main)/Header.js
  src/app/(main)/about/page.js
  src/app/(main)/about/page.module.css
  src/app/(main)/work/[id]/page.js
  src/app/(main)/work/page.js
  src/app/(main)/works/[id]/page.js
  src/app/(main)/works/[id]/page.module.css
  src/app/(main)/works/page.js
  src/app/(main)/works/page.module.css
  src/components/works/DetailAbout.js
  src/components/works/DetailArtist.js
  src/components/works/DetailGuestBook.js
  src/components/works/DetailHeader.js
  src/components/works/DetailHeader.module.css
  src/components/works/DetailReservation.js
  src/components/works/MockData.js
Labels: Feature, Style, Interaction

#19 Sprint/about page#10
  .eslintrc.json
  public/logo/atc-title.svg
  public/logo/axt-logo.png
  src/app/(main)/about/page.js
  src/app/(main)/about/page.module.css
Labels: Style

#20 Sprint/onboard page#11
  package-lock.json
  package.json
  src/app/(onboard)/onboard/page.js
  src/app/(onboard)/onboard/page.module.css
  src/components/onboard/Scene.jsx
Labels: Style, Interaction
