Repository rmdnps10/ATC2024, pull requests merged in 2024-11, with the labels that each got.

#27 works page + map page
  jsconfig.json
  package-lock.json
  package.json
  public/images/map/4f.svg
  public/images/map/4floor.svg
  public/images/map/5f.svg
  public/images/map/5floor.svg
  public/images/map/Arrow_right.png
  public/images/map/loyola.svg
  public/images/works/Rectangle.jpg
  public/images/works/Rectangle10.jpg
  public/images/works/Rectangle13.jpg
  src/app/(main)/about/page.module.css
  src/app/(main)/credit/page.module.css
  src/app/(main)/map/page.js
  src/app/(main)/map/page.module.css
  src/app/(main)/works/page.js
  src/app/(main)/works/page.module.css
  src/components/works/MockData.js
Labels: Feature, Style

#37 전시 작품 조회 API 구현
  src/app/api/works/[id]/route.js
  src/app/api/works/route.js
  src/models/detail-work-schema.js
  src/models/work-schema.js
Labels: Feature

#52 mainpage 반응형 구현
  package-lock.json
  package.json
  public/images/main/Asset1.png
  public/images/main/atc24_profile.png
  public/images/main/branding/Asset3.png
  public/images/main/branding/Asset4.png
  public/images/main/branding/Asset5.png
  public/images/main/branding/Asset6.png
  public/images/main/branding/Asset7.png
  public/images/main/branding/Asset8.png
  public/model/cake.glb
  public/model/star1.glb
  public/model/star2.glb
  public/model/star3.glb
  public/model/star4.glb
  public/model/star5.glb
  public/model/starmain.glb
  src/app/(main)/page.js
  src/app/(main)/page.module.css
  src/components/main/AtomModel.js
  src/components/main/Boxes.js
  src/components/main/CameraController.js
  src/components/main/CustomCursor.module.css
  src/components/main/Effects.js
  src/components/main/Experience.js
  src/components/main/Floor.js
  src/components/main/Model.js
  src/components/main/Overlay.js
  src/components/main/Overlay.module.css
  src/components/main/ThreeText.js
  src/components/main/VideoText.js
  src/components/main/Wall.js
  src/components/main/fish.js
  src/components/main/fish2.js
  src/components/main/main.js
  src/components/main/v2.js
Labels: Style, Interaction

#57 program page
  public/icon/button/toggle.svg
  public/icon/button/toggleUp.svg
  src/app/(main)/program/page.js
  src/app/(main)/program/page.module.css
Labels: Style, Interaction

#56 about page
  public/icon/logo/atc_slogan_horizontal_black.png
  public/icon/logo/atc_slogan_vertical_black.png
  public/images/image 3.png
  public/logo/BARO.svg
  public/logo/atc-title.svg
  public/logo/axt-logo.png
  public/logo/futurelab.svg
  public/logo/smilegate_orange.svg
  public/logo/urbanbeesseoul.svg
  public/logo/교육부.svg
  public/logo/점선면작가.svg
  src/app/(main)/about/page.js
  src/app/(main)/about/page.module.css
  src/components/about/InfiniteBanner.js
  src/components/about/InfiniteBanner.module.css
  src/components/about/ToCreditPage.module.css
  src/components/about/TypingDescription.module.css
Labels: Feature, Style

#55 works, work detail, maps
  next.config.mjs
  package-lock.json
  package.json
  public/images/map/edited5floor.svg
  public/images/works/back.svg
  public/images/works/branding1.svg
  public/images/works/branding2.svg
  public/images/works/branding3.svg
  public/images/works/branding4.svg
  public/images/works/branding5.svg
  public/images/works/branding6.svg
  public/images/works/branding7.svg
  src/app/(main)/map/page.js
  src/app/(main)/map/page.module.css
  src/app/(main)/works/[id]/page.js
  src/app/(main)/works/[id]/page.module.css
  src/app/(main)/works/page.js
  src/app/(main)/works/page.module.css
  src/client-api/putWorkDetail.js
  src/components/map/FifthFloor.js
  src/components/map/FourthFloor.js
  src/components/map/Loyola.js
  src/components/map/d.js
  src/components/works/DetailGuestBook.js
  src/components/works/GuesBook.module.css
  src/components/works/GuestBook.js
  src/components/works/WorkDetailModal.js
  src/components/works/WorkDetailModal.module.css
Labels: Feature, Interaction

#62 11/11 works page
  src/app/(main)/map/page.js
  src/app/(main)/map/page.module.css
  src/app/(main)/works/[id]/page.js
  src/app/(main)/works/[id]/page.module.css
  src/app/(main)/works/page.js
  src/app/(main)/works/page.module.css
  src/components/map/FifthFloor.js
  src/components/map/FourthFloor.js
  src/components/map/Loyola.js
  src/components/works/GuesBook.module.css
  src/components/works/GuestBook.js
  src/components/works/WorkDetailModal.module.css
Labels: Style, Interaction

#73 반응형 수정, 기타 오류 수정
  public/images/map/editedloyola.svg
  src/app/(main)/map/page.js
  src/app/(main)/map/page.module.css
  src/app/(main)/works/[id]/page.module.css
  src/app/(main)/works/page.js
  src/app/(main)/works/page.module.css
  src/components/map/Loyola.js
  src/components/works/GuesBook.module.css
  src/components/works/WorkDetailModal.module.css
Labels: Bug

#72 Feat: about페이지로 가는 인터랙션 및 버튼 #12
  src/components/main/Experience.js
  src/components/main/Experience.jsx
  src/components/main/Floor.js
  src/components/main/Model.js
  src/components/main/Overlay.js
  src/components/main/Overlay.module.css
  src/components/main/ScrollArrow.js
Labels: Style, Interaction

#75 11/14 maps 인터랙션 수정
  src/app/(main)/map/page.js
  src/app/(main)/map/page.module.css
  src/app/(main)/works/[id]/page.js
  src/components/map/FifthFloor.js
  src/components/map/FourthFloor.js
  src/components/map/Loyola.js
  src/components/works/ModalPortal.js
  src/components/works/WorkDetailModal.module.css
Labels: Bug, Style

#87 Refactor/works page#67
  next.config.mjs
  src/app/(main)/works/[id]/page.js
  src/app/(main)/works/[id]/page.module.css
  src/app/(main)/works/page.js
  src/app/(main)/works/page.module.css
Labels: Bug, Feature, Style

#90 메인페이지에서 about 페이지 표시 빨리 하기
  src/components/main/Overlay.js
  src/components/main/ScrollArrow.js
Labels: Style

#101 mainpage 브라우저별 에러 해결
  src/components/main/AtomModel.js
  src/components/main/Experience.js
  src/components/main/Experience.jsx
  src/components/main/Floor.js
  src/components/main/Model.js
  src/components/main/ScrollArrow.js
  src/components/main/ThreeText.js
  src/components/main/Wall.js
Labels: Bug

#113 Feat: 영상팀 유튜브 영상 링크 다시 적용 #11
  src/components/onboard/MyPortal.jsx
Labels: Interaction

#114 Chore: 작품팀 인스타그램 아이디 수정 #12
  src/app/(main)/credit/store/staff.js
  src/components/main/AtomModel.js
  src/hooks/.gitkeep
Labels: Docs
